# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: chatbot-ui

---

# Secret for API Key
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1WSFlTYS1kQWVBcnYzUTh4blpxVThPTzJTdGpQaklhYnlDU3FTYVlWQk5IdTdfcFNS
Uml4X0NXek01TDJ6a2ljQ18td3FZZ1UyRlQzQmxia0ZKSUtrcWVSUHFabkZLcXlUV3R3cHUzMmVD
TnFWa2FsR1ppWTlVR2RLR0h0bmRaYmlEQTZ6eEhQSE9pUTZLX3lpZW5QUGhhcVVaOEE=  # Replace this with your base64-encoded API key

---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      containers:
        - name: chatbot-ui
          image: lakshu/chatbot-ui:latest
          resources: {}
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-ui
                  key: OPENAI_API_KEY

---

# Service
apiVersion: v1
kind: Service
metadata:
  namespace: chatbot-ui
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: chatbot-ui
  type: LoadBalancer
